services:
  mqtt-broker:
    image: eclipse-mosquitto:latest
    container_name: fraud_mqtt_broker
    ports:
      - "1883:1883"
    volumes:
      - ./src/data_ingestion/mosquitto/data:/mosquitto/data
      - ./src/data_ingestion/mosquitto/log:/mosquitto/log

  mlflow:
    image: ghcr.io/mlflow/mlflow:v3.10.0
    container_name: fraud_mlflow
    ports:
      - "5123:5000"
    volumes:
      - ./data/mlflow:/mlflow
    command:
      - mlflow
      - server
      - --host
      - 0.0.0.0
      - --port
      - "5000"
      - --backend-store-uri
      - sqlite:////mlflow/fraud_detection.db
      - --default-artifact-root
      - mlflow-artifacts:/
      - --artifacts-destination
      - /mlflow/artifacts

  grafana:
    image: grafana/grafana-oss:latest
    container_name: fraud_grafana
    ports:
      - "3123:3000" #admin,1122311223
    environment:
      GF_INSTALL_PLUGINS: frser-sqlite-datasource
    volumes:
      - grafana-data:/var/lib/grafana
      - ./data:/project-data:ro

  serving-api:
    build: .
    container_name: fraud_serving_api
    depends_on:
      - mqtt-broker
      - mlflow
    ports:
      - "8000:8000"
    environment:
      FRAUD_BROKER_HOST: mqtt-broker
      FRAUD_BROKER_PORT: "1883"
      FRAUD_MLFLOW_URI: http://mlflow:5000
    volumes:
      - ./data:/app/data
      - ./reports:/app/reports
    command:
      - uvicorn
      - src.serving.app:app
      - --host
      - 0.0.0.0
      - --port
      - "8000"

  training:
    build: .
    container_name: fraud_training
    profiles:
      - jobs
    depends_on:
      - mlflow
    environment:
      FRAUD_MLFLOW_URI: http://mlflow:5000
    volumes:
      - ./data:/app/data
      - ./reports:/app/reports
    command:
      - python
      - -m
      - src.training.train

  monitoring:
    build: .
    container_name: fraud_monitoring
    profiles:
      - jobs
    volumes:
      - ./data:/app/data
      - ./reports:/app/reports
    command:
      - python
      - -m
      - src.monitoring.drift

  orchestration:
    build: .
    container_name: fraud_orchestration
    profiles:
      - jobs
    depends_on:
      - mlflow
    environment:
      FRAUD_MLFLOW_URI: http://mlflow:5000
    volumes:
      - ./data:/app/data
      - ./reports:/app/reports
    command:
      - python
      - -m
      - src.orchestration.flows

volumes:
  grafana-data:
